# Generated by Django 5.0.6 on 2024-06-15 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('img', models.ImageField(upload_to='images/countries/')),
            ],
        ),
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=45)),
                ('paid', models.BooleanField(default=False)),
                ('payment_type', models.CharField(choices=[('0', 'Cash On Delivery'), ('1', 'Visa'), ('2', 'Master Card'), ('3', 'Apple Pay'), ('4', 'Google Pay'), ('5', 'KNET Pay')], default='0', max_length=1)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('0', 'Pending'), ('1', 'Shipped'), ('2', 'Delivered')], default='0', max_length=1)),
                ('delivery_address', models.CharField(max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriesTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_parent', models.BooleanField(default=False)),
                ('level', models.IntegerField(default=0)),
                ('img', models.ImageField(upload_to='images/categories/')),
                ('parent_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.categoriestree')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=128, null=True)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('client_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_addresses', to='core.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='main_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientaddress'),
        ),
        migrations.CreateModel(
            name='ClientPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=45)),
                ('client_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_phones', to='core.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='main_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientphone'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sell_price', models.FloatField(blank=True, null=True)),
                ('purchase_price', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=255, null=True)),
                ('how_to_use', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField()),
                ('offer', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=45, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('category_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoriestree')),
                ('country_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.country')),
            ],
        ),
        migrations.CreateModel(
            name='ItemImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/item/')),
                ('item_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_img', to='core.item')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('item_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.item')),
                ('order_master_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='core.ordermaster')),
            ],
        ),
    ]
